#!/bin/sh

AT() {
  cmd=$1
  echo "$cmd"

  gl_modem -B 1-1.2 AT "$cmd"
}

if [ $# -eq 0 ]; then
  AT 'ATI'
  AT 'AT+QSPN'
  AT 'AT+QNWPREFCFG="mode_pref"'
  AT 'AT+QNWPREFCFG="nsa_nr5g_band"'
  AT 'AT+QNWPREFCFG="lte_band"'
  AT 'AT+QCAINFO'
  AT 'AT+QENG="servingcell"'
  AT 'AT+QENG="neighbourcell"'
else
  AT "$@"
fi
