#!/bin/sh /etc/rc.common

START=95
STOP=10
USE_PROCD=1

start_service() {
    local enabled
    config_load quectel
    config_get_bool enabled led_bars enabled 1
    [ "$enabled" = "1" ] || return 0

    procd_open_instance
    procd_set_param command /usr/bin/5g-led-bars
    procd_set_param respawn 60 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "quectel"
}
