#!/bin/sh /etc/rc.common

START=96
STOP=10
USE_PROCD=1

start_service() {
    local enabled device iface
    config_load quectel
    config_get_bool enabled mbim_watchdog enabled 1
    [ "$enabled" = "1" ] || return 0

    config_get device mbim_watchdog device "/dev/wwan0mbim0"
    config_get iface mbim_watchdog iface "wwan"

    [ -c "$device" ] || return 0

    procd_open_instance
    procd_set_param command /usr/bin/mbim-watchdog -d "$device" -i "$iface"
    procd_set_param respawn 30 5 0
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "quectel"
}
